language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: Vhec56uuNI3NJYXR5owxn8iJIfpAaYieM7LHAvMRiqrU2TGb3G6InNrZyMM8k1umamR8CBx5A26g4jqAZnfAYM2zUT8myXH6tVHa6lKpSeJi6QBz+1iWV5tcbAVbAFFh2Yhu+m97L8ruDebp8cqd80e0Wm8ln2Nm392JPeGW3LlD8eNP8ptPHkfCBHGEk/0r4SaT/dPzFrzwmOZ9cX6N8Urcb85b6/IbsXf0dUC72x8VBEHVHWpsXTodTQVkzzRY+WYHicLDJ39v9ESc3wwBao5GESotEvV4jTRnd7KBxIUybTefQ+dn/nvDYQ0NZYSBP+Xtdqo2+0RU2pdnc5rkg4CfBV90gPlNvOtH9tA5sMESv6Bq2P5IlKSK3alQ66WfoxZKAD65MEnDFLL8OuxPyHssip3N2Cug6I5nwtiXyAWjWdrFbB+J6RwfXb+GUaFe+6Qn4atngv+6EdMqFUvFsZ+S8qSp3DiGokjGw30dL8rF0rSy2s11Mp5uQqN3Xg6EEbPqOQ6dbkiVhHUsa34W0dmSM4EvysYzp5yfVX29YeqYRcV2GTKahIjoJVt57zUCdh1VhvQ4CI2Mh6dGSK0KqYg5onCd9LMKzJwnxvd6UV/tIHhOtHW5GlH2cXMHa/FC3CwWa3J04TuhRVnNXjy2+U73P9qGNp0jFfSdH0t55ac=
